version: '3.1'

services:
  web:
    image: richarvey/nginx-php-fpm:latest
    restart: "no"
    ports:
      - 127.0.0.1:8080:80
  db:
    build:
      context: .
      dockerfile: ./tools/docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 127.0.0.1:3306:3306