version: '3.1'

services:
  web:
    image: richarvey/nginx-php-fpm:latest
    restart: "no"
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./:/var/www:consistent
    environment:
      ERRORS: 1
      ENABLE_XDEBUG: 1
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_autostart=1 default_enable=0 remote_enable=1 remote_connect_back=0 remote_port=9005 idekey=PHPSTORM"
      PHP_IDE_CONFIG: serverName=PHPSTORM
  db:
    build:
      context: .
      dockerfile: ./tools/docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 127.0.0.1:3306:3306