database:
  host: "localhost"
  username: "root"
  password: "1234"
  name: "web-test"
  port: "3306"
routes:
  home:
    controller: Jarenal\App\Controller\Home
    action: "index"
    method: "GET"
    pattern: "/"